function DataStructure = importSNAPpixels(filename, startRow, endRow)
% importSNAPpixels : Read pixel values exported from ESA SNAP
%
% Example:
% pixData = importSNAPpixels('S3Images/S3A_OL_1_EFR____20160605T074147_20160605T074447_20160606T174711_0180_005_049_3419_LN1_O_NT_001_geometry_Mask.txt');
%
% The returned structure fields are
%     PixelX,PixelY,Longitude,Latitude,Oa01_radiance,Oa02_radiance,Oa03_radiance, ...
%     Oa04_radiance,Oa05_radiance,Oa06_radiance,Oa07_radiance,Oa08_radiance, ...
%     Oa09_radiance,Oa10_radiance,Oa11_radiance,Oa12_radiance,Oa13_radiance, ...
%     Oa14_radiance,Oa15_radiance,Oa16_radiance,Oa17_radiance,Oa18_radiance, ...
%     Oa19_radiance,Oa20_radiance,Oa21_radiance,altitude,latitude,longitude, ...
%     detector_index,FWHM_band_1,FWHM_band_2,FWHM_band_3,FWHM_band_4, ...
%     FWHM_band_5,FWHM_band_6,FWHM_band_7,FWHM_band_8,FWHM_band_9, ...
%     FWHM_band_10,FWHM_band_11,FWHM_band_12,FWHM_band_13,FWHM_band_14, ...
%     FWHM_band_15,FWHM_band_16,FWHM_band_17,FWHM_band_18,FWHM_band_19, ...
%     FWHM_band_20,FWHM_band_21,frame_offset,lambda0_band_1,lambda0_band_2, ...
%     lambda0_band_3,lambda0_band_4,lambda0_band_5,lambda0_band_6, ...
%     lambda0_band_7,lambda0_band_8,lambda0_band_9,lambda0_band_10, ...
%     lambda0_band_11,lambda0_band_12,lambda0_band_13,lambda0_band_14, ...
%     lambda0_band_15,lambda0_band_16,lambda0_band_17,lambda0_band_18, ...
%     lambda0_band_19,lambda0_band_20,lambda0_band_21,solar_flux_band_1, ...
%     solar_flux_band_2,solar_flux_band_3,solar_flux_band_4, ...
%     solar_flux_band_5,solar_flux_band_6,solar_flux_band_7, ...
%     solar_flux_band_8,solar_flux_band_9,solar_flux_band_10, ...
%     solar_flux_band_11,solar_flux_band_12,solar_flux_band_13, ...
%     solar_flux_band_14,solar_flux_band_15,solar_flux_band_16, ...
%     solar_flux_band_17,solar_flux_band_18,solar_flux_band_19, ...
%     solar_flux_band_20,solar_flux_band_21,quality_flags] = ...

%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/06/09 12:55:22

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 7;
    endRow = inf;
end

% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow(1)-1, 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    textscan(fileID, '%[^\n\r]', startRow(block)-1, 'ReturnOnError', false);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
DataStructure.PixelX = dataArray{:, 1};
DataStructure.PixelY = dataArray{:, 2};
DataStructure.Longitude = dataArray{:, 3};
DataStructure.Latitude = dataArray{:, 4};
DataStructure.Oa01_radiance = dataArray{:, 5};
DataStructure.Oa02_radiance = dataArray{:, 6};
DataStructure.Oa03_radiance = dataArray{:, 7};
DataStructure.Oa04_radiance = dataArray{:, 8};
DataStructure.Oa05_radiance = dataArray{:, 9};
DataStructure.Oa06_radiance = dataArray{:, 10};
DataStructure.Oa07_radiance = dataArray{:, 11};
DataStructure.Oa08_radiance = dataArray{:, 12};
DataStructure.Oa09_radiance = dataArray{:, 13};
DataStructure.Oa10_radiance = dataArray{:, 14};
DataStructure.Oa11_radiance = dataArray{:, 15};
DataStructure.Oa12_radiance = dataArray{:, 16};
DataStructure.Oa13_radiance = dataArray{:, 17};
DataStructure.Oa14_radiance = dataArray{:, 18};
DataStructure.Oa15_radiance = dataArray{:, 19};
DataStructure.Oa16_radiance = dataArray{:, 20};
DataStructure.Oa17_radiance = dataArray{:, 21};
DataStructure.Oa18_radiance = dataArray{:, 22};
DataStructure.Oa19_radiance = dataArray{:, 23};
DataStructure.Oa20_radiance = dataArray{:, 24};
DataStructure.Oa21_radiance = dataArray{:, 25};
DataStructure.altitude = dataArray{:, 26};
DataStructure.latitude = dataArray{:, 27};
DataStructure.longitude = dataArray{:, 28};
DataStructure.detector_index = dataArray{:, 29};
DataStructure.FWHM_band_1 = dataArray{:, 30};
DataStructure.FWHM_band_2 = dataArray{:, 31};
DataStructure.FWHM_band_3 = dataArray{:, 32};
DataStructure.FWHM_band_4 = dataArray{:, 33};
DataStructure.FWHM_band_5 = dataArray{:, 34};
DataStructure.FWHM_band_6 = dataArray{:, 35};
DataStructure.FWHM_band_7 = dataArray{:, 36};
DataStructure.FWHM_band_8 = dataArray{:, 37};
DataStructure.FWHM_band_9 = dataArray{:, 38};
DataStructure.FWHM_band_10 = dataArray{:, 39};
DataStructure.FWHM_band_11 = dataArray{:, 40};
DataStructure.FWHM_band_12 = dataArray{:, 41};
DataStructure.FWHM_band_13 = dataArray{:, 42};
DataStructure.FWHM_band_14 = dataArray{:, 43};
DataStructure.FWHM_band_15 = dataArray{:, 44};
DataStructure.FWHM_band_16 = dataArray{:, 45};
DataStructure.FWHM_band_17 = dataArray{:, 46};
DataStructure.FWHM_band_18 = dataArray{:, 47};
DataStructure.FWHM_band_19 = dataArray{:, 48};
DataStructure.FWHM_band_20 = dataArray{:, 49};
DataStructure.FWHM_band_21 = dataArray{:, 50};
DataStructure.frame_offset = dataArray{:, 51};
DataStructure.lambda0_band_1 = dataArray{:, 52};
DataStructure.lambda0_band_2 = dataArray{:, 53};
DataStructure.lambda0_band_3 = dataArray{:, 54};
DataStructure.lambda0_band_4 = dataArray{:, 55};
DataStructure.lambda0_band_5 = dataArray{:, 56};
DataStructure.lambda0_band_6 = dataArray{:, 57};
DataStructure.lambda0_band_7 = dataArray{:, 58};
DataStructure.lambda0_band_8 = dataArray{:, 59};
DataStructure.lambda0_band_9 = dataArray{:, 60};
DataStructure.lambda0_band_10 = dataArray{:, 61};
DataStructure.lambda0_band_11 = dataArray{:, 62};
DataStructure.lambda0_band_12 = dataArray{:, 63};
DataStructure.lambda0_band_13 = dataArray{:, 64};
DataStructure.lambda0_band_14 = dataArray{:, 65};
DataStructure.lambda0_band_15 = dataArray{:, 66};
DataStructure.lambda0_band_16 = dataArray{:, 67};
DataStructure.lambda0_band_17 = dataArray{:, 68};
DataStructure.lambda0_band_18 = dataArray{:, 69};
DataStructure.lambda0_band_19 = dataArray{:, 70};
DataStructure.lambda0_band_20 = dataArray{:, 71};
DataStructure.lambda0_band_21 = dataArray{:, 72};
DataStructure.solar_flux_band_1 = dataArray{:, 73};
DataStructure.solar_flux_band_2 = dataArray{:, 74};
DataStructure.solar_flux_band_3 = dataArray{:, 75};
DataStructure.solar_flux_band_4 = dataArray{:, 76};
DataStructure.solar_flux_band_5 = dataArray{:, 77};
DataStructure.solar_flux_band_6 = dataArray{:, 78};
DataStructure.solar_flux_band_7 = dataArray{:, 79};
DataStructure.solar_flux_band_8 = dataArray{:, 80};
DataStructure.solar_flux_band_9 = dataArray{:, 81};
DataStructure.solar_flux_band_10 = dataArray{:, 82};
DataStructure.solar_flux_band_11 = dataArray{:, 83};
DataStructure.solar_flux_band_12 = dataArray{:, 84};
DataStructure.solar_flux_band_13 = dataArray{:, 85};
DataStructure.solar_flux_band_14 = dataArray{:, 86};
DataStructure.solar_flux_band_15 = dataArray{:, 87};
DataStructure.solar_flux_band_16 = dataArray{:, 88};
DataStructure.solar_flux_band_17 = dataArray{:, 89};
DataStructure.solar_flux_band_18 = dataArray{:, 90};
DataStructure.solar_flux_band_19 = dataArray{:, 91};
DataStructure.solar_flux_band_20 = dataArray{:, 92};
DataStructure.solar_flux_band_21 = dataArray{:, 93};
DataStructure.quality_flags = dataArray{:, 94};
DataStructure.all_radiance = cell2mat(dataArray(:, 5:25));
DataStructure.all_solar_flux = cell2mat(dataArray(:, 73:93));
DataStructure.all_FWHM = cell2mat(dataArray(:, 30:51));
DataStructure.all_lambda0 = cell2mat(dataArray(:, 52:72));
return