function [Wavelength,SReflect,PReflect,STransmit,PTransmit,SAbsorb,PAbsorb,SPhaseT,PPhaseT,SPhaseR,PPhaseR,DiattT,DiattR,RetardT,RetardR] = importZemaxReflWv(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [WAVELENGTH,SREFLECT,PREFLECT,STRANSMIT,PTRANSMIT,SABSORB,PABSORB,SPHASET,PPHASET,SPHASER,PPHASER,DIATTT,DIATTR,RETARDT,RETARDR]
%   = importZemaxReflWv(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [WAVELENGTH,SREFLECT,PREFLECT,STRANSMIT,PTRANSMIT,SABSORB,PABSORB,SPHASET,PPHASET,SPHASER,PPHASER,DIATTT,DIATTR,RETARDT,RETARDR]
%   = importZemaxReflWv(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [Wavelength,SReflect,PReflect,STransmit,PTransmit,SAbsorb,PAbsorb,SPhaseT,PPhaseT,SPhaseR,PPhaseR,DiattT,DiattR,RetardT,RetardR]
%   = importZemaxReflWv('SeaWaterReflectanceZemax14.TXT',9, 409);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/06/12 11:12:46

%% Initialize variables.
if nargin<=2
    startRow = 9;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%10f%11f%11f%11f%11f%11f%11f%11f%11f%11f%11f%11f%11f%11f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow(1)-1, 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    textscan(fileID, '%[^\n\r]', startRow(block)-1, 'ReturnOnError', false);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Wavelength = dataArray{:, 1};
SReflect = dataArray{:, 2};
PReflect = dataArray{:, 3};
STransmit = dataArray{:, 4};
PTransmit = dataArray{:, 5};
SAbsorb = dataArray{:, 6};
PAbsorb = dataArray{:, 7};
SPhaseT = dataArray{:, 8};
PPhaseT = dataArray{:, 9};
SPhaseR = dataArray{:, 10};
PPhaseR = dataArray{:, 11};
DiattT = dataArray{:, 12};
DiattR = dataArray{:, 13};
RetardT = dataArray{:, 14};
RetardR = dataArray{:, 15};

